#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/agate

PRODUCT_COPY_FILES += \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_device.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/PlaybackVolAna_CeRegion_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_CeRegion_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/PlaybackVolDigi_CeRegion_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_CeRegion_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/aurisys_config_hifi3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_hifi3.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/aurisys_param/FV-SAM-MTKXX.dat:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_param/FV-SAM-MTKXX.dat \
    vendor/xiaomi/agate/proprietary/vendor/etc/aurisys_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_param/Speech_AudioParam.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/CFR_para_HD.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_HD.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/CFR_para_M.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_M.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/CFR_para_T.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_T.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/CFR_para_UW.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_UW.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/CFR_para_W.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_UW.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_UW.dat \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/ai_scene.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ai_scene.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/almalence_sr_params_UW_upscale.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_UW_upscale.config \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/almalence_sr_params_tele.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_tele.config \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/almalence_sr_params_wide.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_wide.config \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/apu_miai_capture.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/apu_miai_capture.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/apu_miai_preview.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/apu_miai_preview.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.golden \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/deblur_sd_opencl_binary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_sd_opencl_binary.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/deblur_sd_opencl_params.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_sd_opencl_params.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/hdrcheckerparamsettings.yml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdrcheckerparamsettings.yml \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/intsense_config_optical_zoom.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/intsense_config_optical_zoom.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/com.xiaomi_k11t_mecp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/com.xiaomi_k11t_mecp.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/com.xiaomi_k11t_mecp_for_nocali.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/com.xiaomi_k11t_mecp_for_nocali.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/com.xiaomi_k11t_mecp_hwdepth_bokeh.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/com.xiaomi_k11t_mecp_hwdepth_bokeh.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/dof_model/capture_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/dof_model/capture_cache \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/dof_model/capture_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/dof_model/capture_model \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/dof_model/capture_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/dof_model/capture_policy \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/fusion_models/fusion_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/fusion_models/fusion_cache \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/fusion_models/fusion_mecp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/fusion_models/fusion_mecp.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/fusion_models/fusion_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/fusion_models/fusion_model \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/fusion_models/fusion_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/fusion_models/fusion_policy \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/rt_model/preview_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/rt_model/preview_cache \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/rt_model/preview_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/rt_model/preview_model \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/jiiganmodel/rt_model/preview_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/rt_model/preview_policy \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/libal_fpc_tuning.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/libal_fpc_tuning.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/miai_hdr_config.yaml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/miai_hdr_config.yaml \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/reiddetv2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/reiddetv2.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/reiddetv2_apu_cache.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/reiddetv2_apu_cache.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/reiddetv2_ocl_kernel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/reiddetv2_ocl_kernel.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/reiddetv2_ocl_param.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/reiddetv2_ocl_param.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/sr_params.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_params.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/video_bokeh_apu_front_20210413.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/video_bokeh_apu_front_20210413.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/dualbokehsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/dualbokehsnapshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/frontbokehsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontbokehsnapshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/frontsinglesnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontsinglesnapshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/frontsupernightsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontsupernightsnapshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/manualsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/manualsnapshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/normalpreview.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/normalpreview.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/normalsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/normalsnapshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/satsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/satsnapshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/superhdsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/superhdsnapshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/superlowlightsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/superlowlightsnapshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/thirdpartysnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/thirdpartysnapshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/camera/xiaomi/uwsuperlowlightshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/uwsuperlowlightshot.json \
    vendor/xiaomi/agate/proprietary/vendor/etc/cust_color.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/cust_silky_brightness.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_silky_brightness.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/xiaomi/agate/proprietary/vendor/etc/mdss_dsi_k11t_42_02_0a_dsc_cmd_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mdss_dsi_k11t_42_02_0a_dsc_cmd_mi.xml \
    vendor/xiaomi/agate/proprietary/vendor/etc/misound_res.bin:$(TARGET_COPY_OUT_VENDOR)/etc/misound_res.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/misound_res_headphone.bin:$(TARGET_COPY_OUT_VENDOR)/etc/misound_res_headphone.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/misound_res_spk.bin:$(TARGET_COPY_OUT_VENDOR)/etc/misound_res_spk.bin \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermal-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-class0.conf \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-mgame.conf \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermal-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-navigation.conf \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermal-region-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-region-map.conf \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermal-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-video.conf \
    vendor/xiaomi/agate/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/agate/proprietary/vendor/firmware/RCV-cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RCV-cs35l41-dsp1-spk-cali.bin \
    vendor/xiaomi/agate/proprietary/vendor/firmware/RCV-cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RCV-cs35l41-dsp1-spk-prot.bin \
    vendor/xiaomi/agate/proprietary/vendor/firmware/cs35l41-delta-rcv-handset.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-delta-rcv-handset.txt \
    vendor/xiaomi/agate/proprietary/vendor/firmware/cs35l41-delta-rcv-handsfree.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-delta-rcv-handsfree.txt \
    vendor/xiaomi/agate/proprietary/vendor/firmware/cs35l41-delta-rcv-music.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-delta-rcv-music.txt \
    vendor/xiaomi/agate/proprietary/vendor/firmware/cs35l41-delta-spk-handsfree.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-delta-spk-handsfree.txt \
    vendor/xiaomi/agate/proprietary/vendor/firmware/cs35l41-delta-spk-music.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-delta-spk-music.txt \
    vendor/xiaomi/agate/proprietary/vendor/firmware/cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-cali.bin \
    vendor/xiaomi/agate/proprietary/vendor/firmware/cs35l41-dsp1-spk-cali.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-cali.wmfw \
    vendor/xiaomi/agate/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.bin \
    vendor/xiaomi/agate/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.wmfw \
    vendor/xiaomi/agate/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu

PRODUCT_PACKAGES += \
    audio.primary.mt6893 \
    libaudio_param_parser-vnd \
    libfvaudio \
    libmisound \
    libmisoundcrossfade \
    agateimx355_mipi_raw_IdxMgr \
    agateimx355_mipi_raw_tuning \
    agateov16a1q_mipi_raw_IdxMgr \
    agateov16a1q_mipi_raw_tuning \
    agateov64b40_mipi_raw_IdxMgr \
    agateov64b40_mipi_raw_tuning \
    agates5k5e9_mipi_raw_IdxMgr \
    agates5k5e9_mipi_raw_tuning \
    agates5khm2_mipi_raw_IdxMgr \
    agates5khm2_mipi_raw_tuning \
    com.xiaomi.plugin.capbokeh \
    com.xiaomi.plugin.dc \
    com.xiaomi.plugin.depurple \
    com.xiaomi.plugin.hdr \
    com.xiaomi.plugin.ldc \
    com.xiaomi.plugin.memcpy \
    com.xiaomi.plugin.miaideblur \
    com.xiaomi.plugin.miaihdr \
    com.xiaomi.plugin.miaiie \
    com.xiaomi.plugin.mibokeh \
    com.xiaomi.plugin.mifragment \
    com.xiaomi.plugin.misegment \
    com.xiaomi.plugin.rawsuperlight \
    com.xiaomi.plugin.skinbeautifier \
    com.xiaomi.plugin.sr \
    com.xiaomi.plugin.superlowlight \
    com.xiaomi.plugin.supernight \
    com.xiaomi.plugin.swflip \
    com.xiaomi.plugin.tetrassr \
    com.xiaomi.plugin.uwfusion \
    android.hardware.camera.provider@2.6-impl-mediatek \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist.models \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.aishutter.models \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_agateimx355mipiraw_3rd_Capture \
    libCamera_agateimx355mipiraw_3rd_Preview \
    libCamera_agateimx355mipiraw_3rd_Video \
    libCamera_agateimx355mipiraw_EIS_Video_1080P \
    libCamera_agateimx355mipiraw_EIS_Video_1080P_Zoom1 \
    libCamera_agateimx355mipiraw_EIS_Video_1080P_Zoom2 \
    libCamera_agateimx355mipiraw_EIS_Video_1080P_Zoom3 \
    libCamera_agateimx355mipiraw_EIS_Video_720P \
    libCamera_agateimx355mipiraw_EIS_Video_720P_Zoom1 \
    libCamera_agateimx355mipiraw_EIS_Video_720P_Zoom2 \
    libCamera_agateimx355mipiraw_EIS_Video_720P_Zoom3 \
    libCamera_agateimx355mipiraw_Face_Capture \
    libCamera_agateimx355mipiraw_Face_Preview \
    libCamera_agateimx355mipiraw_Flash_Capture \
    libCamera_agateimx355mipiraw_Flash_Preview \
    libCamera_agateimx355mipiraw_HDR_Face_Capture \
    libCamera_agateimx355mipiraw_HDR_Scene_Capture \
    libCamera_agateimx355mipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_agateimx355mipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_agateimx355mipiraw_HDR_Scene_Capture_Zoom3 \
    libCamera_agateimx355mipiraw_LLHDR_Face_Capture \
    libCamera_agateimx355mipiraw_LLHDR_Scene_Capture \
    libCamera_agateimx355mipiraw_Professional_Capture \
    libCamera_agateimx355mipiraw_Professional_Preview \
    libCamera_agateimx355mipiraw_QQWechat_VideoCall \
    libCamera_agateimx355mipiraw_Scene_Capture \
    libCamera_agateimx355mipiraw_Scene_Capture_Zoom1 \
    libCamera_agateimx355mipiraw_Scene_Capture_Zoom2 \
    libCamera_agateimx355mipiraw_Scene_Capture_Zoom3 \
    libCamera_agateimx355mipiraw_Scene_Preview \
    libCamera_agateimx355mipiraw_Scene_Preview_Zoom1 \
    libCamera_agateimx355mipiraw_Scene_Preview_Zoom2 \
    libCamera_agateimx355mipiraw_Scene_Preview_Zoom3 \
    libCamera_agateimx355mipiraw_SuperNightRaw_Capture \
    libCamera_agateimx355mipiraw_SuperNightRaw_Preview \
    libCamera_agateimx355mipiraw_Video_1080P \
    libCamera_agateimx355mipiraw_Video_1080P_Zoom1 \
    libCamera_agateimx355mipiraw_Video_1080P_Zoom2 \
    libCamera_agateimx355mipiraw_Video_1080P_Zoom3 \
    libCamera_agateimx355mipiraw_Video_720P \
    libCamera_agateimx355mipiraw_Video_720P_Zoom1 \
    libCamera_agateimx355mipiraw_Video_720P_Zoom2 \
    libCamera_agateimx355mipiraw_Video_720P_Zoom3 \
    libCamera_agateimx355mipiraw_portrait_capture_full \
    libCamera_agateimx355mipiraw_portrait_preview_full \
    libCamera_agateov16a1qmipiraw_3rd_Capture \
    libCamera_agateov16a1qmipiraw_3rd_Preview \
    libCamera_agateov16a1qmipiraw_3rd_Video \
    libCamera_agateov16a1qmipiraw_FaceUnlock_Capture \
    libCamera_agateov16a1qmipiraw_Face_Capture \
    libCamera_agateov16a1qmipiraw_FrontLight_Capture \
    libCamera_agateov16a1qmipiraw_FrontLight_Preview \
    libCamera_agateov16a1qmipiraw_HDR_Capture \
    libCamera_agateov16a1qmipiraw_Panorama_Capture \
    libCamera_agateov16a1qmipiraw_Portrait_Capture \
    libCamera_agateov16a1qmipiraw_Portrait_Preview \
    libCamera_agateov16a1qmipiraw_QQWeChat_Preview \
    libCamera_agateov16a1qmipiraw_QQWechat_Video \
    libCamera_agateov16a1qmipiraw_QQWechat_VideoCall \
    libCamera_agateov16a1qmipiraw_Scene_Capture \
    libCamera_agateov16a1qmipiraw_Scene_Preview \
    libCamera_agateov16a1qmipiraw_Short_Video \
    libCamera_agateov16a1qmipiraw_SuperNightLight_Capture \
    libCamera_agateov16a1qmipiraw_SuperNightLight_Preview \
    libCamera_agateov16a1qmipiraw_SuperNight_Capture \
    libCamera_agateov16a1qmipiraw_SuperNight_Preview \
    libCamera_agateov16a1qmipiraw_VideoHDR_1080P \
    libCamera_agateov16a1qmipiraw_VideoHDR_1080P_Reconfig \
    libCamera_agateov16a1qmipiraw_VideoHDR_720P \
    libCamera_agateov16a1qmipiraw_VideoHDR_720P_Reconfig \
    libCamera_agateov16a1qmipiraw_Video_1080P \
    libCamera_agateov16a1qmipiraw_Video_1080P_EIS \
    libCamera_agateov16a1qmipiraw_Video_720P \
    libCamera_agateov16a1qmipiraw_Video_720P_120fps \
    libCamera_agateov16a1qmipiraw_Video_720P_EIS \
    libCamera_agateov64b40mipiraw_3rd_Capture \
    libCamera_agateov64b40mipiraw_3rd_Capture_1080P \
    libCamera_agateov64b40mipiraw_AIShutter_Capture \
    libCamera_agateov64b40mipiraw_AIShutter_Preview \
    libCamera_agateov64b40mipiraw_Face_Capture \
    libCamera_agateov64b40mipiraw_Face_Capture_64M \
    libCamera_agateov64b40mipiraw_Face_Capture_CE \
    libCamera_agateov64b40mipiraw_Face_Capture_Upscale \
    libCamera_agateov64b40mipiraw_Face_Preview \
    libCamera_agateov64b40mipiraw_Flash_A_Capture \
    libCamera_agateov64b40mipiraw_Flash_A_Preview \
    libCamera_agateov64b40mipiraw_Flash_A_Preview_zoom1 \
    libCamera_agateov64b40mipiraw_HDR_Face_Capture \
    libCamera_agateov64b40mipiraw_HDR_Scene_Capture \
    libCamera_agateov64b40mipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_agateov64b40mipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_agateov64b40mipiraw_LLHDR_Face_Capture \
    libCamera_agateov64b40mipiraw_LLHDR_Scene_Capture \
    libCamera_agateov64b40mipiraw_Panorama_Capture \
    libCamera_agateov64b40mipiraw_QQ_Preview \
    libCamera_agateov64b40mipiraw_Scene_Capture \
    libCamera_agateov64b40mipiraw_Scene_Capture_64M \
    libCamera_agateov64b40mipiraw_Scene_Capture_CE \
    libCamera_agateov64b40mipiraw_Scene_Capture_Magic \
    libCamera_agateov64b40mipiraw_Scene_Capture_Professional \
    libCamera_agateov64b40mipiraw_Scene_Capture_Upscale \
    libCamera_agateov64b40mipiraw_Scene_Capture_Zoom1 \
    libCamera_agateov64b40mipiraw_Scene_Capture_Zoom2 \
    libCamera_agateov64b40mipiraw_Scene_Capture_inSensorZoom1 \
    libCamera_agateov64b40mipiraw_Scene_Capture_inSensorZoom2 \
    libCamera_agateov64b40mipiraw_Scene_Preview \
    libCamera_agateov64b40mipiraw_Scene_Preview_Zoom1 \
    libCamera_agateov64b40mipiraw_Scene_Preview_Zoom2 \
    libCamera_agateov64b40mipiraw_Scene_Professional_Preview \
    libCamera_agateov64b40mipiraw_SuperNightRaw_Capture \
    libCamera_agateov64b40mipiraw_SuperNightRaw_Preview \
    libCamera_agateov64b40mipiraw_SuperNightSE_Capture \
    libCamera_agateov64b40mipiraw_Video_1080P \
    libCamera_agateov64b40mipiraw_Video_1080P_60fps \
    libCamera_agateov64b40mipiraw_Video_1080P_60fps_EIS \
    libCamera_agateov64b40mipiraw_Video_1080P_60fps_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_1080P_60fps_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_1080P_EIS \
    libCamera_agateov64b40mipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_1080P_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_1080P_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_4k \
    libCamera_agateov64b40mipiraw_Video_4k_EIS \
    libCamera_agateov64b40mipiraw_Video_4k_EIS_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_4k_EIS_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_4k_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_4k_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_720P \
    libCamera_agateov64b40mipiraw_Video_720P_120fps \
    libCamera_agateov64b40mipiraw_Video_720P_120fps_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_720P_120fps_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_720P_240fps \
    libCamera_agateov64b40mipiraw_Video_720P_240fps_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_720P_240fps_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_720P_EIS \
    libCamera_agateov64b40mipiraw_Video_720P_EIS_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_720P_EIS_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_720P_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_720P_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_Capture \
    libCamera_agateov64b40mipiraw_Video_Enhance_1080P \
    libCamera_agateov64b40mipiraw_Video_Enhance_1080P_EIS \
    libCamera_agateov64b40mipiraw_Video_Enhance_1080P_Reconfig \
    libCamera_agateov64b40mipiraw_Video_Enhance_1080P_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_Enhance_1080P_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_Enhance_4K \
    libCamera_agateov64b40mipiraw_Video_Enhance_4K_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_Enhance_4K_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_Enhance_720P \
    libCamera_agateov64b40mipiraw_Video_Enhance_720P_EIS \
    libCamera_agateov64b40mipiraw_Video_Enhance_720P_Zoom1 \
    libCamera_agateov64b40mipiraw_Video_Enhance_720P_Zoom2 \
    libCamera_agateov64b40mipiraw_Video_Log \
    libCamera_agateov64b40mipiraw_WeChatQQ_Video \
    libCamera_agateov64b40mipiraw_WeChat_Preview \
    libCamera_agateov64b40mipiraw_XTS_Capture \
    libCamera_agateov64b40mipiraw_portrait_capture_full \
    libCamera_agateov64b40mipiraw_portrait_preview_full \
    libCamera_agates5k5e9mipiraw_Face_Capture \
    libCamera_agates5k5e9mipiraw_Face_Preview \
    libCamera_agates5k5e9mipiraw_Flash_A_Capture \
    libCamera_agates5k5e9mipiraw_Flash_A_Preview \
    libCamera_agates5k5e9mipiraw_Panorama_Capture \
    libCamera_agates5k5e9mipiraw_Scene_Capture \
    libCamera_agates5k5e9mipiraw_Scene_Capture_Zoom1 \
    libCamera_agates5k5e9mipiraw_Scene_Capture_Zoom2 \
    libCamera_agates5k5e9mipiraw_Scene_Preview \
    libCamera_agates5k5e9mipiraw_Scene_Preview_Zoom1 \
    libCamera_agates5k5e9mipiraw_Scene_Preview_Zoom2 \
    libCamera_agates5k5e9mipiraw_Video_1080P \
    libCamera_agates5k5e9mipiraw_Video_1080P_Zoom1 \
    libCamera_agates5k5e9mipiraw_Video_1080P_Zoom2 \
    libCamera_agates5k5e9mipiraw_Video_720P \
    libCamera_agates5k5e9mipiraw_Video_720P_Zoom1 \
    libCamera_agates5k5e9mipiraw_Video_720P_Zoom2 \
    libCamera_agates5k5e9mipiraw_Video_Capture \
    libCamera_agates5k5e9mipiraw_XTS_Capture \
    libCamera_agates5khm2mipiraw_3rd_Capture \
    libCamera_agates5khm2mipiraw_3rd_Capture_1080P \
    libCamera_agates5khm2mipiraw_AIShutter_Capture \
    libCamera_agates5khm2mipiraw_Face_Capture \
    libCamera_agates5khm2mipiraw_Face_Capture_108M \
    libCamera_agates5khm2mipiraw_Face_Capture_CE \
    libCamera_agates5khm2mipiraw_Face_Preview \
    libCamera_agates5khm2mipiraw_Flash_A_Capture \
    libCamera_agates5khm2mipiraw_Flash_A_Preview \
    libCamera_agates5khm2mipiraw_Flash_A_Preview_zoom1 \
    libCamera_agates5khm2mipiraw_HDR_Face_Capture \
    libCamera_agates5khm2mipiraw_HDR_Scene_Capture \
    libCamera_agates5khm2mipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_agates5khm2mipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_agates5khm2mipiraw_LLHDR_Face_Capture \
    libCamera_agates5khm2mipiraw_LLHDR_Scene_Capture \
    libCamera_agates5khm2mipiraw_Panorama_Capture \
    libCamera_agates5khm2mipiraw_QQ_Preview \
    libCamera_agates5khm2mipiraw_Scene_Capture \
    libCamera_agates5khm2mipiraw_Scene_Capture_108M \
    libCamera_agates5khm2mipiraw_Scene_Capture_CE \
    libCamera_agates5khm2mipiraw_Scene_Capture_Professional \
    libCamera_agates5khm2mipiraw_Scene_Capture_Zoom1 \
    libCamera_agates5khm2mipiraw_Scene_Capture_Zoom2 \
    libCamera_agates5khm2mipiraw_Scene_Capture_inSensorZoom1 \
    libCamera_agates5khm2mipiraw_Scene_Capture_inSensorZoom2 \
    libCamera_agates5khm2mipiraw_Scene_Preview \
    libCamera_agates5khm2mipiraw_Scene_Preview_Zoom1 \
    libCamera_agates5khm2mipiraw_Scene_Preview_Zoom2 \
    libCamera_agates5khm2mipiraw_Scene_Professional_Preview \
    libCamera_agates5khm2mipiraw_SuperNightRaw_Capture \
    libCamera_agates5khm2mipiraw_SuperNightRaw_Preview \
    libCamera_agates5khm2mipiraw_SuperNightSE_Capture \
    libCamera_agates5khm2mipiraw_Video_1080P \
    libCamera_agates5khm2mipiraw_Video_1080P_60fps \
    libCamera_agates5khm2mipiraw_Video_1080P_60fps_EIS \
    libCamera_agates5khm2mipiraw_Video_1080P_60fps_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_1080P_60fps_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_1080P_EIS \
    libCamera_agates5khm2mipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_1080P_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_1080P_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_4k \
    libCamera_agates5khm2mipiraw_Video_4k_EIS \
    libCamera_agates5khm2mipiraw_Video_4k_EIS_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_4k_EIS_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_4k_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_4k_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_720P \
    libCamera_agates5khm2mipiraw_Video_720P_120fps \
    libCamera_agates5khm2mipiraw_Video_720P_120fps_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_720P_120fps_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_720P_240fps \
    libCamera_agates5khm2mipiraw_Video_720P_240fps_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_720P_240fps_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_720P_EIS \
    libCamera_agates5khm2mipiraw_Video_720P_EIS_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_720P_EIS_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_720P_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_720P_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_Capture \
    libCamera_agates5khm2mipiraw_Video_Enhance_1080P \
    libCamera_agates5khm2mipiraw_Video_Enhance_1080P_EIS \
    libCamera_agates5khm2mipiraw_Video_Enhance_1080P_Reconfig \
    libCamera_agates5khm2mipiraw_Video_Enhance_1080P_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_Enhance_1080P_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_Enhance_4K \
    libCamera_agates5khm2mipiraw_Video_Enhance_4K_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_Enhance_4K_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_Enhance_720P \
    libCamera_agates5khm2mipiraw_Video_Enhance_720P_EIS \
    libCamera_agates5khm2mipiraw_Video_Enhance_720P_Zoom1 \
    libCamera_agates5khm2mipiraw_Video_Enhance_720P_Zoom2 \
    libCamera_agates5khm2mipiraw_Video_Log \
    libCamera_agates5khm2mipiraw_WeChatQQ_Video \
    libCamera_agates5khm2mipiraw_WeChat_Preview \
    libCamera_agates5khm2mipiraw_XTS_Capture \
    libCamera_agates5khm2mipiraw_portrait_capture_full \
    libCamera_agates5khm2mipiraw_portrait_preview_full \
    libHalSuperSensorServer \
    libHalSuperSensorServerCWrapper \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libSuperSensor \
    libSuperSensorCPU \
    libSuperSensorProcessor \
    lib_bsscore \
    lib_sr_models \
    libaaa_ltm \
    libaaa_ltmx \
    libaiawb_moon \
    libaiawb_moon_model \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaiawb_sun_model \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libainrcore \
    libalCFR \
    libalLDC \
    libalhLDC \
    libanc_calibration_parser \
    libanc_dc_base \
    libarcsoft_beautyshot \
    libarcsoft_distortion_correction \
    libarcsoft_dualcam_refocus \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_portrait_lighting \
    libarcsoft_portrait_lighting_c \
    libarcsoft_sn_mtk_apu \
    libarcsoft_super_night_raw \
    libarcsoft_supernight \
    libbeauty_face_interface \
    libc++_shared \
    libcam.ArcCamEngine \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.seninfn3d \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.3dnr \
    libcamalgo.aibc \
    libcamalgo.aidepth \
    libcamalgo.aihdr \
    libcamalgo.ainr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.utility \
    libcamalgo.vaidepth \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera_scene \
    libcameracustom.eis \
    libcameracustom \
    libcom.xiaomi.pluginutils \
    libdip_drv \
    libdip_imem \
    libdip_postproc \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libfocus \
    libheichal \
    libimagebuffer_wrapper \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libimgsensorca \
    libispcameraca \
    liblpcnr \
    libmfllcore \
    libmiai_deblur \
    libmiai_portraitsupernight \
    libmialgo_ie_capture \
    libmialgo_sd \
    libmialgo_utils \
    libmialgo_video_enhance \
    libmialgoengine \
    libmialgoengine2 \
    libmibokeh_845_video \
    libmibokeh_mt6873 \
    libmpbase \
    libmsnr \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdcalibration \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_cameraplatforminfoxiaomi \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkcam_vsync_util \
    libmtkisp_metadata \
    librelight_only \
    libsdk_sr \
    libstereoinfoaccessor_vsdof \
    libvideofilter_only \
    libvidhance \
    libvidhance_active_ois \
    libvidhance_autozoom \
    libvidhance_calibration_tool \
    libvidhance_face_stabilizer \
    libvidhance_horizon_correction \
    libvidhance_ldc \
    libvidhance_stabilizer \
    libvidhance_super_stabilization \
    libwa_depth \
    libwa_opticalzoom_fusion \
    libwa_opticalzoomfactor \
    libwa_refocus \
    libwa_rtdof \
    libwa_rtrefocus \
    libwa_sat \
    libxmi_high_dynamic_range \
    libmtkcam_streaminfo_plugin-p1stt \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.device@3.7 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    batterysecret \
    camerahalserver \
    lib3a.ccu.ddr \
    lib3a.ccu.dm \
    lib3a.ccu.pm \
    mi_thermald
